# Utilise une base Debian pour avoir accès facilement à LibreOffice et Java
FROM eclipse-temurin:21-jre-jammy

# Installation de LibreOffice
RUN apt-get update && apt-get install -y \
    libreoffice \
    && rm -rf /var/lib/apt/lists/*

# Création des dossiers de travail
RUN mkdir -p /tools /output

# Ton JAR doit être injecté via un volume au runtime, 
# mais tu peux aussi le copier ici si la version ne change pas souvent.
# COPY ./tools/sonar-cnes-report-5.0.4.jar /tools/

WORKDIR /output